### PR TITLE
Catch possessives with ’ (right single quotation mark)

### PR DESCRIPTION
**Pull request by jdbaldry**
Found in https://github.com/grafana/website/pull/20363/files#diff-33bcdea2dcb5b53fb71bae08c05fd9fadeb28804226f7b629e09f019a26365f3R37

### CODE REVIEW

**Review by clayton-cornell — APPROVED** [review]
Looks good. Is there any "rule" for cleaning up right single quotes vs straight? Do we need to care?

**Comment by clayton-cornell** [comment]
I've seen a real mix. Not sure what inserts smart quotes. My editors default to straight single and double qotes.

**Comment by jdbaldry** [comment]
> I've seen a real mix. Not sure what inserts smart quotes. My editors default to straight single and double qotes.

I think it may be a Mac feature: https://support.apple.com/en-gb/guide/mac-help/mh35735/mac#:~:text=the%20command%20again.-,Use%20smart%20quotes%20and%20dashes,-Automatically%20convert%20straight

**Comment by jdbaldry** [comment]
I'm gonna merge this for now but if I come across another issue with smart quotes, I'll refactor the linting rules to separately catch those characters.

**Pull request merged**
