### PR TITLE
docs: adds saturations

### PR DESCRIPTION
**Pull request by chri2547**
This PR adds the plural "saturations" to the word list. This is a common terms used throughout the Asserts docs.

### CODE REVIEW

**Review by clayton-cornell — APPROVED** [review]
LGTM

Edit: I didn't dig into this one....

**Comment by chri2547** [comment]
> I don't have a strong understanding of the actual language rules but I found a reference that matches my internal feeling:
> 
> > The noun saturation can be countable or uncountable.
> > In more general, commonly used, contexts, the plural form will also be saturation.

@jdbaldry , that's fine, I changed to singular. It just reads funny to me being part of a list where all other list items are plural. But I'll go with your finding, thanks for the research! I think we can close the PR then.

**Comment by clayton-cornell** [comment]
FWIW, `saturations` is a plural of `saturation` in the Oxford dictionary. It really depends on context though.

**Comment by chri2547** [comment]
> FWIW, `saturations` is a plural of `saturation` in the Oxford dictionary. It really depends on context though.

I think singular is fine. I'm already starting to get used to it! :) 

Thanks for thinking this through with me!

**Comment by chri2547** [comment]
Decided to not include the plural form of "saturation" in the word list.

**Comment by jdbaldry** [comment]
Thank you for contributing anyway, the PR is useful even if it isn't merged :)

**Comment by chri2547** [comment]
> Thank you for contributing anyway, the PR is useful even if it isn't merged :)

Indeed, quite useful!

**Pull request closed without merging**
