### PR TITLE
Docs: Add CMS to Headings yml file

### PR DESCRIPTION
**Pull request by imatwawana**

### CODE REVIEW

**Review by clayton-cornell — APPROVED** [review]

**Comment by clayton-cornell** [comment]
The docs here: https://grafana.com/docs/writers-toolkit/review/lint-prose/rules/#grafanaheadings say you can add spelling exceptions to the `Headings.yml` so this PR looked OK according to that information.

**Comment by imatwawana** [comment]
What @clayton-cornell said

**Comment by jdbaldry** [comment]
> The docs here: [grafana.com/docs/writers-toolkit/review/lint-prose/rules#grafanaheadings](https://grafana.com/docs/writers-toolkit/review/lint-prose/rules/#grafanaheadings) say you can add spelling exceptions to the `Headings.yml` so this PR looked OK according to that information.

I'll need to update that too, thanks for highlighting it :)

**Comment by imatwawana** [comment]
So do I need to update this file as well then:
https://github.com/grafana/writers-toolkit/tree/main/vale/dictionary

**Pull request merged**
